name: PyPI Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and publish
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository-url https://upload.pypi.org/legacy/ -u GiamoSalerno -p Data2304 dist/*